image: maven:3.8.3-jdk-11
clone:
  depth: full    # SonarCloud scanner needs the full history to assign issues properly
  
  definitions:
  caches:
    sonar: ~/.sonar/cache  # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        script:
          - mvn -B org.jacoco:jacoco-maven-plugin:prepare-agent verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
        artifacts:
          - target/**
    - step: &build-test
        name: Build and test
        caches:
          - maven
        script:
          - mvn -B verify
        artifacts:
          - target/**
    - step: &build-test-createTar
          name: build, test and create Tar
          script:
            - mvn clean install
            - IMAGE_NAME=product-service-docker
            - docker build . --file Dockerfile --tag ${IMAGE_NAME}
            - docker save ${IMAGE_NAME} --output "${IMAGE_NAME}.tar"
          services:
            - docker
          caches:
            - docker
          artifacts:
            - "*.tar"
    - step: &deploy
          name: Deploy to Production
          deployment: Production
          script:
            - echo ${DOCKERHUB_PASSWORD} | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            - IMAGE_NAME=product-service-docker
            - docker load --input "${IMAGE_NAME}.tar"
            - VERSION="prod-0.1.${BITBUCKET_BUILD_NUMBER}"
            - IMAGE=${DOCKERHUB_USERNAME}/${IMAGE_NAME}
            - docker tag "${IMAGE_NAME}" "${IMAGE}:latest"
            - docker push "${IMAGE}:latest"
          services:
            - docker


pipelines:
  default:
  - step: *build-test
  branches:
    master:
      - step: *build-test-createTar
      - step: *deploy
    development: 
          - step: *build-test-sonarcloud
    pull-requests:
      - step: *build-test-sonarcloud